# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Weather.create(weather_type: "Sunny")
Weather.create(weather_type: "Cloudy")
Weather.create(weather_type: "Rainy")
Weather.create(weather_type: "Thunder Storm")

Mood.create(emoji: "Happy")
Mood.create(emoji: "Sad")
Mood.create(emoji: "Angry")
Mood.create(emoji: "Blah")

Playlist.create(mood_id: 1, weather_id: 1)
Playlist.create(mood_id: 2, weather_id: 1)
Playlist.create(mood_id: 3, weather_id: 1)
Playlist.create(mood_id: 2, weather_id: 4)
Playlist.create(mood_id: 2, weather_id: 1)
Playlist.create(mood_id: 3, weather_id: 3)
Playlist.create(mood_id: 3, weather_id: 2)
Playlist.create(mood_id: 1, weather_id: 3)
Playlist.create(mood_id: 3, weather_id: 3)
Playlist.create(mood_id: 3, weather_id: 1)
Playlist.create(mood_id: 4, weather_id: 3)
Playlist.create(mood_id: 1, weather_id: 4)
Playlist.create(mood_id: 4, weather_id: 1)
Playlist.create(mood_id: 1, weather_id: 2)


Song.create(mood_id: 1, weather_id: 4, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "jIS3KouPdgM")
Song.create(mood_id: 2, weather_id: 1, playlist_id: 3, song_name: "Guess ", artist_name: "face", url: "jIS3KouPdgM")
Song.create(mood_id: 4, weather_id: 2, playlist_id: 4, song_name: " Who's Back", artist_name: "Scar", url: "jIS3KouPdgM")
Song.create(mood_id: 3, weather_id: 3, playlist_id: 2, song_name: "Back", artist_name: "Scarf", url: "jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
# Song.create(mood_id: 1, weather_id: 1, playlist_id: 1, song_name: "Guess Who's Back", artist_name: "Scarface", url: "https://www.youtube.com/watch?v=jIS3KouPdgM")
